spring:
  cloud:
    stream:
      bindings:
        to-uppercase-request:
          destination: to-uppercase-request
        to-uppercase-reply:
          destination: to-uppercase-reply
        input:
          destination: to-uppercase-request
        output:
          destination: to-uppercase-reply
